# 函数们的整体配置信息
Conf:
  component: "serverless-global"
  inputs:
    region: ap-hongkong
    runtime: Python3.6
    handler: index.main_handler
    include_common: ./common
    blog_user: Anycodes
    blog_email: service@anycodes.cn
    blog_about_me: 毕业于浙江大学，硕士学历，目前在腾讯工作，著有《Serverless 架构》一书，是Serverless架构的热衷者，曾做一款叫Anycodes的软件，目前下载超过80万次。
    blog_host: www.0duzhan.com
    website_title: 刘宇的博客
    website_keywords: 刘宇的博客
    website_description: 这是刘宇的个人博客：刘宇，毕业于浙江大学，硕士学历，目前在腾讯工作，著有《Serverless 架构》一书，是Serverless架构的热衷者，曾做一款叫Anycodes的软件，目前下载超过80万次。
    website_bucket: serverless-blog-demo-1256773370
    mysql_host: 
    mysql_user: 
    mysql_password: 
    mysql_port: 
    mysql_db: 
    admin_user: serverless
    admin_password: serverless
    tencent_secret_id:
    tencent_secret_key:
    tencent_appid: 1256773370


# 网站
CosBucket:
  component: '@serverless/tencent-website'
  inputs:
    code:
      root: website/dist
      src: ./
      index: list.html
    region:  ${Conf.region}
    bucketName: ${Conf.website_bucket}
#     hosts:
#       - host: 0duzhan.com
#         https:
#           certId: awPsOIHY
#           forceSwitch: -1
#       - host: www.0duzhan.com
#         https:
#           certId: awPsOIHY
#           forceSwitch: -1
    env:
      apiUrl: ${APIService.subDomain}

# 各个函数的单独配置
Blog_Web_addComment:
  component: "@serverless/tencent-scf"
  inputs:
    name: Blog_Web_addComment
    description: 添加评论
    codeUri: ./cloudFunctions/addComment
    handler: ${Conf.handler}
    runtime: ${Conf.runtime}
    region:  ${Conf.region}
    include:
      - ${Conf.include_common}
    environment:
      variables:
        mysql_host: ${Conf.mysql_host}
        mysql_port: ${Conf.mysql_port}
        mysql_user: ${Conf.mysql_user}
        mysql_password: ${Conf.mysql_password}
        mysql_db: ${Conf.mysql_db}

Blog_Web_getArticleContent:
  component: "@serverless/tencent-scf"
  inputs:
    name: Blog_Web_getArticleContent
    description: 获取文章内容
    codeUri: ./cloudFunctions/getArticleContent
    handler: ${Conf.handler}
    runtime: ${Conf.runtime}
    region:  ${Conf.region}
    include:
      - ${Conf.include_common}
    environment:
      variables:
        mysql_host: ${Conf.mysql_host}
        mysql_port: ${Conf.mysql_port}
        mysql_user: ${Conf.mysql_user}
        mysql_password: ${Conf.mysql_password}
        mysql_db: ${Conf.mysql_db}


Blog_Web_getArticleList:
  component: "@serverless/tencent-scf"
  inputs:
    name: Blog_Web_getArticleList
    description: 获取分类下文章列表
    codeUri: ./cloudFunctions/getArticleList
    handler: ${Conf.handler}
    runtime: ${Conf.runtime}
    region:  ${Conf.region}
    include:
      - ${Conf.include_common}
    environment:
      variables:
        mysql_host: ${Conf.mysql_host}
        mysql_port: ${Conf.mysql_port}
        mysql_user: ${Conf.mysql_user}
        mysql_password: ${Conf.mysql_password}
        mysql_db: ${Conf.mysql_db}

Blog_Web_getHotArticleList:
  component: "@serverless/tencent-scf"
  inputs:
    name: Blog_Web_getHotArticleList
    description: 获取热门文章列表
    codeUri: ./cloudFunctions/getHotArticleList
    handler: ${Conf.handler}
    runtime: ${Conf.runtime}
    region:  ${Conf.region}
    include:
      - ${Conf.include_common}
    environment:
      variables:
        mysql_host: ${Conf.mysql_host}
        mysql_port: ${Conf.mysql_port}
        mysql_user: ${Conf.mysql_user}
        mysql_password: ${Conf.mysql_password}
        mysql_db: ${Conf.mysql_db}

Blog_Web_getCategoryList:
  component: "@serverless/tencent-scf"
  inputs:
    name: Blog_Web_getCategoryList
    description: 获取分类列表
    codeUri: ./cloudFunctions/getCategoryList
    handler: ${Conf.handler}
    runtime: ${Conf.runtime}
    region:  ${Conf.region}
    include:
      - ${Conf.include_common}
    environment:
      variables:
        mysql_host: ${Conf.mysql_host}
        mysql_port: ${Conf.mysql_port}
        mysql_user: ${Conf.mysql_user}
        mysql_password: ${Conf.mysql_password}
        mysql_db: ${Conf.mysql_db}

Blog_Web_getTagsList:
  component: "@serverless/tencent-scf"
  inputs:
    name: Blog_Web_getTagsList
    description: 获取标签列表
    codeUri: ./cloudFunctions/getTagsList
    handler: ${Conf.handler}
    runtime: ${Conf.runtime}
    region:  ${Conf.region}
    include:
      - ${Conf.include_common}
    environment:
      variables:
        mysql_host: ${Conf.mysql_host}
        mysql_port: ${Conf.mysql_port}
        mysql_user: ${Conf.mysql_user}
        mysql_password: ${Conf.mysql_password}
        mysql_db: ${Conf.mysql_db}

Blog_Web_getComments:
  component: "@serverless/tencent-scf"
  inputs:
    name: Blog_Web_getComments
    description: 获取评论列表
    codeUri: ./cloudFunctions/getComments
    handler: ${Conf.handler}
    runtime: ${Conf.runtime}
    region:  ${Conf.region}
    include:
      - ${Conf.include_common}
    environment:
      variables:
        mysql_host: ${Conf.mysql_host}
        mysql_port: ${Conf.mysql_port}
        mysql_user: ${Conf.mysql_user}
        mysql_password: ${Conf.mysql_password}
        mysql_db: ${Conf.mysql_db}

Blog_Web_updateArticleWatched:
  component: "@serverless/tencent-scf"
  inputs:
    name: Blog_Web_updateArticleWatched
    description: 增加文章阅读量
    codeUri: ./cloudFunctions/updateArticleWatched
    handler: ${Conf.handler}
    runtime: ${Conf.runtime}
    region:  ${Conf.region}
    include:
      - ${Conf.include_common}
    environment:
      variables:
        mysql_host: ${Conf.mysql_host}
        mysql_port: ${Conf.mysql_port}
        mysql_user: ${Conf.mysql_user}
        mysql_password: ${Conf.mysql_password}
        mysql_db: ${Conf.mysql_db}

Blog_Web_getSentence:
  component: "@serverless/tencent-scf"
  inputs:
    name: Blog_Web_getSentence
    description: 获取名言警句
    codeUri: ./cloudFunctions/getSentence
    handler: ${Conf.handler}
    runtime: ${Conf.runtime}
    region:  ${Conf.region}
    include:
      - ${Conf.include_common}

Blog_Admin:
  component: '@serverless/tencent-scf'
  inputs:
    name: Blog_Admin
    description: 后台服务
    codeUri: ./cloudFunctions/admin
    handler: ${Conf.handler}
    runtime: ${Conf.runtime}
    region:  ${Conf.region}
    memorySize: 1024
    timeout: 300
    include:
      - ${Conf.include_common}
    environment:
      variables:
        mysql_host: ${Conf.mysql_host}
        mysql_port: ${Conf.mysql_port}
        mysql_user: ${Conf.mysql_user}
        mysql_password: ${Conf.mysql_password}
        mysql_db: ${Conf.mysql_db}
        admin_user: ${Conf.admin_user}
        admin_password: ${Conf.admin_password}
        tencent_secret_id: ${Conf.tencent_secret_id}
        tencent_secret_key: ${Conf.tencent_secret_key}
        tencent_appid: ${Conf.tencent_appid}
        region: ${Conf.region}
        website_bucket: ${Conf.website_bucket}

Blog_Admin_updateArticle:
  component: "@serverless/tencent-scf"
  inputs:
    name: Blog_Admin_updateArticle
    description: 文章修改和增加后的动作
    codeUri: ./cloudFunctions/updateArticle
    handler: ${Conf.handler}
    runtime: ${Conf.runtime}
    region:  ${Conf.region}
    memorySize: 512
    timeout: 100
    include:
      - ${Conf.include_common}
    environment:
      variables:
        mysql_host: ${Conf.mysql_host}
        mysql_port: ${Conf.mysql_port}
        mysql_user: ${Conf.mysql_user}
        mysql_password: ${Conf.mysql_password}
        mysql_db: ${Conf.mysql_db}
        region: ${Conf.region}

#Blog_Tools_uploadPicture:
#  component: '@serverless/tencent-scf'
#  inputs:
#    name: Blog_Tools_uploadPicture
#    description: 后台服务
#    codeUri: ./cloudFunctions/uploadPicture
#    handler: ${Conf.handler}
#    runtime: ${Conf.runtime}
#    region:  ${Conf.region}
#    memorySize: 1024
#    timeout: 300
#    include:
#      - ${Conf.include_common}
#    environment:
#      variables:
#        tencent_secret_id: ${Conf.tencent_secret_id}
#        tencent_secret_key: ${Conf.tencent_secret_key}
#        tencent_appid: ${Conf.tencent_appid}
#        region: ${Conf.region}
#        website_bucket: ${Conf.website_bucket}

# 创建API网关Service
APIService:
  component: "@serverless/tencent-apigateway"
  inputs:
    region: ${Conf.region}
#     customDomain:
#       - domain: api.0duzhan.com
#         isDefaultMapping: 'FALSE'
#         pathMappingSet:
#           - path: /
#             environment: release
#         protocols:
#           - http
    protocols:
      - http
      - https
    serviceName: Serverless_blog
    environment: release
    endpoints:
      - path: /web/comment/add
        description: 添加评论
        method: POST
        enableCORS: TRUE
        function:
          functionName: Blog_Web_addComment
      - path: /web/article/content/get
        description: 获取文章内容
        method: POST
        enableCORS: TRUE
        function:
          functionName: Blog_Web_getArticleContent
      - path: /web/article/list/get
        description: 获取分类下文章列表
        method: POST
        enableCORS: TRUE
        function:
          functionName: Blog_Web_getArticleList
      - path: /web/category/list/get
        description: 获取分类列表
        method: POST
        enableCORS: TRUE
        function:
          functionName: Blog_Web_getCategoryList
      - path: /web/comment/get
        description: 获取评论列表
        method: POST
        enableCORS: TRUE
        function:
          functionName: Blog_Web_getComments
      - path: /web/article/watched/update
        description: 增加文章阅读量
        method: POST
        enableCORS: TRUE
        function:
          functionName: Blog_Web_updateArticleWatched
      - path: /web/sentence/get
        description: 获取名言警句
        method: POST
        enableCORS: TRUE
        function:
          functionName: Blog_Web_getSentence
      - path: /web/article/list/hot/get
        description: 获取分类下文章列表
        method: POST
        enableCORS: TRUE
        function:
          functionName: Blog_Web_getHotArticleList
      - path: /web/tags/list/get
        description: 获取标签列表
        method: POST
        enableCORS: TRUE
        function:
          functionName: Blog_Web_getTagsList
      - path: /admin
        description: 后台服务
        method: ANY
        serviceTimeout: 300
        function:
          functionName: Blog_Admin
          isIntegratedResponse: TRUE
#      - path: /tools/picture/upload
#        description: 上传图片
#        method: POST
#        serviceTimeout: 300
#        enableCORS: TRUE
#        function:
#          functionName: Blog_Tools_uploadPicture
